<?php
declare(strict_types=1);

namespace App\ImportExport\Domain;

/**
 * TASK-127 — the provenance and disclaimer block carried by every export.
 *
 * The AC is that every export is audited *and* carries the disclaimer. Auditing
 * records that the export happened; this block is the part that travels with the
 * bytes, so a file that gets detached from the system still says what it is and
 * is not. The wording is fixed here so all five formats say the same thing.
 */
final class ExportProvenance
{
    /**
     * Deliberately not configurable per request: a caller who can weaken the
     * disclaimer can defeat the point of having one.
     */
    public const DISCLAIMER = 'This export is a point-in-time, unofficial copy of the registry of cadastral/lot data. '
        . 'It is not a certified title document and must not be used as legal proof of ownership or boundary.';

    public function __construct(
        public readonly string $format,
        public readonly string $crsCode,
        public readonly int $rowCount,
        public readonly bool $piiIncluded,
        public readonly int $redactedFieldCount,
        public readonly string $generatedBy,
        public readonly string $layerName,
        public readonly \DateTimeImmutable $generatedAt,
    ) {
    }

    /**
     * Machine-readable form, embedded as a foreign member in GeoJSON, as the
     * gpkg_metadata rows of a GeoPackage and inside the Shapefile sidecar.
     *
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        return [
            'disclaimer'            => self::DISCLAIMER,
            'source_system'         => 'webgis',
            'layer'                 => $this->layerName,
            'format'                => $this->format,
            'crs'                   => $this->crsCode,
            'feature_count'         => $this->rowCount,
            'pii_included'          => $this->piiIncluded,
            'redacted_field_count'  => $this->redactedFieldCount,
            'generated_by'          => $this->generatedBy,
            'generated_at'          => $this->generatedAt->format(\DATE_ATOM),
        ];
    }

    /**
     * Human-readable lines, for formats that have nowhere to put structured
     * metadata (CSV comment header, KML description, sidecar text).
     *
     * @return list<string>
     */
    public function toLines(): array
    {
        return [
            self::DISCLAIMER,
            sprintf('Source: webgis — layer "%s"', $this->layerName),
            sprintf('Format: %s | CRS: %s | Features: %d', $this->format, $this->crsCode, $this->rowCount),
            sprintf(
                'PII: %s',
                $this->piiIncluded
                    ? 'included (caller is permitted)'
                    : sprintf('excluded, %d field(s) redacted', $this->redactedFieldCount)
            ),
            sprintf(
                'Generated by %s at %s',
                $this->generatedBy,
                $this->generatedAt->format(\DATE_ATOM)
            ),
        ];
    }

    /** The whole block as a single newline-joined string. */
    public function toText(): string
    {
        return implode("\n", $this->toLines());
    }
}
